<a href="https://colab.research.google.com/github/Howlbeeb/ML-Projects/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [2]:
 scalar = torch.tensor(7)
 scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [6]:
MATRIX.ndim

2

In [7]:
MATRIX[[1],[1]]

tensor([10])

In [8]:
MATRIX.shape


torch.Size([2, 2])

In [9]:
JAY = torch.tensor([[[[2,3],[4,5]]]])

In [10]:
JAY.shape

torch.Size([1, 1, 2, 2])

In [11]:
JAY.ndim

4

### RANDOM TENSORS


In [12]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4455, 0.4110, 0.8821, 0.9252],
        [0.3508, 0.3082, 0.5064, 0.6579],
        [0.4530, 0.7186, 0.0773, 0.2542]])

In [13]:
random_tensor.ndim

2

In [14]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
ones = torch.ones(4,5)

In [16]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### creating a range of tensors

In [17]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
one_to_1k = torch.arange(start = 1,end=1000,step=100)
one_to_1k

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

### Creating tensors like

In [19]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [23]:
some_tensor = torch.rand(4,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8673, 0.2230, 0.4045, 0.5230],
        [0.2706, 0.3821, 0.7512, 0.4654],
        [0.9213, 0.7272, 0.9244, 0.2277],
        [0.0067, 0.7479, 0.4369, 0.8927]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 4])
Device tensor is on: cpu


In [24]:
tensor = torch.tensor([1,2,3])

In [25]:
tensor + 10

tensor([11, 12, 13])

In [26]:
tensor - 10

tensor([-9, -8, -7])

In [27]:
  %%time
 torch.matmul(tensor,tensor)

CPU times: user 647 µs, sys: 99 µs, total: 746 µs
Wall time: 11.1 ms


tensor(14)

In [28]:
 %%time
 value = 0
 for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.99 ms, sys: 0 ns, total: 1.99 ms
Wall time: 3.11 ms


In [29]:
 torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[1.0206, 1.0520, 1.0749],
        [0.7310, 0.6400, 0.6541],
        [0.6957, 0.6402, 0.5948]])

In [30]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6512, 0.7281],
        [0.6891, 0.7836]])

In [31]:
torch.matmul(torch.rand(10,3),torch.rand(3,10)).shape

torch.Size([10, 10])

In [32]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Using Transpose to change shape

In [33]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [34]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [35]:
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [36]:
X = torch.arange(0,100,10)

In [37]:
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
X.min()

tensor(0)

In [40]:
X.dtype

torch.int64

### Mean can't work on Long only ***float32***

In [42]:
X.type(torch.float32).mean()

tensor(45.)

In [43]:
X.max()

tensor(90)

In [44]:
X.sum()

tensor(450)

In [45]:
torch.sum(X)

tensor(450)

In [46]:
 import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [49]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [53]:
torch.squeeze(z)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
z.shape

torch.Size([1, 9])

In [55]:
torch.squeeze(z).shape


torch.Size([9])